name: Django CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9,]

    env:
      MODE: ${{ secrets.MODE }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Lint with flake
        run: |
          flake8 .
      - name: Run Tests
        run: |
          python manage.py test

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Apply database migrations
        run: python manage.py migrate

  deploy:
    runs-on:  ubuntu-latest
    name: deploy our django application to Heroku
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
        name: Deploy
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "secrets.HEROKU_APP_NAME" #Must be unique in Heroku
          heroku_email: "emery.kroquet@gmail.com"
          branch: "main"
