name: Django CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]

    env:
      MODE: ${{ secrets.MODE }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get install gunicorn -y
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run Tests
        run: |
          python manage.py test

      - name: Restart Gunicorn
        run: sudo systemctl restart gunicorn

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Apply database migrations
        run: python manage.py migrate

      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: emerykroquet/oc-ettings-site
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
